config/routes.rb
Rails.application.routes.draw do

  get 'list' => 'operations#list'
  post 'answer' => 'operations#answer'
  resources :operations

  root 'operations#new'

end

app/models/operation.rb
class Operation
  include Mongoid::Document
  field :firstOp, type: String
  field :secondOp, type: Integer
  field :initTime, type: Time
  field :endTime, type: Time
  field :responseTime, type: Numeric
  field :type, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/operations_controller.rb
require "http"
require 'uri'

class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index

  end

  # GET /operations/list
  # GET /operations/list.json
  def list
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
    r = Random.new
    @operation.firstOp = r.rand(1...99)
    @operation.secondOp = r.rand(1...99)
    @operation.type = ['+','-','*','/'].sample
    @operation.initTime = Time.new
    @operation.save
    url = "http://localhost:5000/predict/?"
    params = URI.encode_www_form([["op1",@operation.firstOp.to_i],
      ["op2",@operation.secondOp.to_i],["opType",@operation.type]])
    url << params
    print url
    @estimatedTime = HTTP.get(url).to_s.gsub(/[\[\]]/, '')
  end

  # POST /operations
  # POST /operations.json
  def answer
    @operation = Operation.find(params[:operation]['id'])

    if ((@operation.type == '+') && (@operation.firstOp.to_i  + @operation.secondOp.to_i  == params[:result].to_i ))
        @valid = true
    elsif ((@operation.type == '-') && (@operation.firstOp.to_i  - @operation.secondOp.to_i  == params[:result].to_i ))
        @valid = true
    elsif ((@operation.type == '*') && (@operation.firstOp.to_i  * @operation.secondOp.to_i  == params[:result].to_i ))
        @valid = true
    elsif ((@operation.type == '/') && (@operation.firstOp.to_i  / @operation.secondOp.to_i  == params[:result].to_i ))
        @valid = true
    else
      render :new
    end

    if (@valid)
      @operation.endTime = Time.new
      @operation.responseTime = (@operation.endTime.to_f - @operation.initTime.to_f)
      @operation.save
      render :answer
    end
  end


  # GET /operations/1/edit
  def edit
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      render :list
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/operations/_form.html.erb
<%= form_for @operation, url: {action: "answer"}, method: :post do |f| %>
  <div class="field">
    <%= @operation.firstOp %> <%= @operation.type %> <%= @operation.secondOp%>  = <%= text_field_tag 'result' %>
  </div>
  <p id="estimatedTime">
    Estimated time: <%= @estimatedTime %>
  </p>


  <%= f.hidden_field :id, :value => @operation.id %>
  <div class="actions">
      <%= f.submit "Enviar" %>
  </div>
  <% end %>

app/views/operations/answer.html.erb
<h1>Correct answer!</h1>
<a href=/> I want more</a>
<a href=/list> See results </a>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/list.html.erb
<h1>Listing operations</h1>

<%= link_to 'New Operation', new_operation_path %>

<table>
  <thead>
    <tr>
      <th>FirstOp</th>
      <th>Type</th>
      <th>SecondOp</th>
      <th>InitTime</th>
      <th>EndTime</th>
      <th>Responsetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.firstOp %></td>
        <td><%= operation.type %></td>
        <td><%= operation.secondOp %></td>
        <td><%= operation.initTime %></td>
        <td><%= operation.endTime %></td>
        <td><%= operation.responseTime %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/operations/new.html.erb
<h1>New operation</h1>
<%= render 'form' %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstop:</strong>
  <%= @operation.firstOp %>
</p>

<p>
  <strong>Secondop:</strong>
  <%= @operation.secondOp %>
</p>

<p>
  <strong>Responsetime:</strong>
  <%= @operation.responseTime %>
</p>

<p>
  <strong>Type:</strong>
  <%= @operation.type %>
</p>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>